package com.bill99.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FileWSDelegate", targetNamespace = "http://ws.bill99.com/")
public interface FileWSDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns byte[]
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDroolsScript", targetNamespace = "http://ws.bill99.com/", className = "com.bill99.ws.GetDroolsScript")
	@ResponseWrapper(localName = "getDroolsScriptResponse", targetNamespace = "http://ws.bill99.com/", className = "com.bill99.ws.GetDroolsScriptResponse")
	public byte[] getDroolsScript(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
